# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Web's End
email: eggoeke@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Is the web ending or are you just on the edge of it? This is a corner of the internet made to burn, to be consumed like flames licking a piece of paper.
baseurl: "/webs-end" # the subpath of your site, e.g. /blog
permalink: /update/:year/:month/:day/:title.html
url: "https://eggoeke.github.io"
twitter_username: eggoeke
github_username:  eggoeke
remote_theme: eggoeke/webs-end
# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-search

  # Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
include:
  - search.json
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

